name: async_value
description: A utility for safely manipulating asynchronous data
version: 0.0.1
# homepage: https://www.example.com
repository: https://github.com/huang12zheng/async_value

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  riverpod: ^2.1.1

dev_dependencies:
  pedantic: ^1.10.0-nullsafety.3
  test: ^1.16.0-nullsafety.17
