name: async_value
description: An utility for safely manipulating asynchronous data
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0-133.2.beta <3.0.0'
  # sdk: '>=2.12.0 <3.0.0'

dependencies:
  freezed_annotation: ^0.13.0-nullsafety.0

dev_dependencies:
  pedantic: ^1.10.0-nullsafety.3
  test: ^1.16.0-nullsafety.17